[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/share/*"
  to = "/.netlify/functions/share?id=:splat"
  status = 200

[[redirects]]
  from = "/share"
  to = "/.netlify/functions/share"
  status = 200
